services:
  minio:
    env_file:
      - ./envs/production/.env.minio
    networks:
      vif_objects:
        aliases:
          - makepad-minio-vif
    volumes:
      - "${MAKEPAD_MINIO_DATA_PATH:-/var/lib/makepad/minio}:/data"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.infra.makepad.minio == true
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 256M

networks:
  objects:
    external: true
    name: ${MAKEPAD_MINIO_CATWLK_OBJECTS_NETWORK}
  vif_objects:
    external: true
    name: ${MAKEPAD_MINIO_VIF_OBJECTS_NETWORK}
